version: '3.4'

services:
  redis:
    image: redis
    command: redis-server --appendonly yes --maxmemory 536870912 --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - .docker-data/redis:/data
